### ISSUE TITLE
vec vs set

### ISSUE THREAD

**Issue by mark-summerfield** [DimaKudosh/difflib#4]
In the sequencematcher the second_sequence_popular is a Vec; but in the Python difflib.py b_popular is a set which may explain why this rust difflib's behavior is different from the Python difflib's behavior.

Also, sequencematcher uses HashMap rather than FnvHashMap (and FnvHashSet for second_sequence_popular); these Fnv- versions should be faster.

**Comment by DimaKudosh** [comment]
I have replaced Vec with HashSet. I didn't use FnvHashMap/FnvHashSet because they are not from standard library and I won't add extra dependency for this.
